# Site settings
title: nuele14
description: 'Pensieri minimali di un Software Engeneer (e spero anche un po di più)'
# url: ''
# baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'nuele14'
  email: nuele14@hotmail.it
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  nuele14
  instagram_username:  nuele14

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: _bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

plugins:
  - jekyll-paginate
  - jekyll-scholar 
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
